package test.testhexagonal.common.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
    NO_ERROR(0, "Sin error"),
    CONTINUE(100, "Continuar"),
    SWITCHING_PROTOCOLS(101, "Cambiando protocolos"),
    PROCESSING(102, "Procesando"),
    OK(200, "OK"),
    CREATED(201, "Creado"),
    ACCEPTED(202, "Aceptado"),
    NON_AUTHORITATIVE_INFORMATION(203, "Información no autoritativa"),
    NO_CONTENT(204, "Sin contenido"),
    RESET_CONTENT(205, "Restablecer contenido"),
    PARTIAL_CONTENT(206, "Contenido parcial"),
    MULTI_STATUS(207, "Multi-estatus"),
    ALREADY_REPORTED(208, "Ya reportado"),
    IM_USED(226, "Soy usado"),
    MULTIPLE_CHOICES(300, "Múltiples opciones"),
    MOVED_PERMANENTLY(301, "Movido permanentemente"),
    FOUND(302, "Encontrado"),
    SEE_OTHER(303, "Ver otro"),
    NOT_MODIFIED(304, "No modificado"),
    USE_PROXY(305, "Usar proxy"),
    SWITCH_PROXY(306, "Cambiar proxy"),
    TEMPORARY_REDIRECT(307, "Redirección temporal"),
    PERMANENT_REDIRECT(308, "Redirección permanente"),
    BAD_REQUEST(400, "Solicitud incorrecta"),
    UNAUTHORIZED(401, "No autorizado"),
    PAYMENT_REQUIRED(402, "Pago requerido"),
    FORBIDDEN(403, "Prohibido"),
    NOT_FOUND(404, "No encontrado"),
    METHOD_NOT_ALLOWED(405, "Método no permitido"),
    NOT_ACCEPTABLE(406, "No aceptable"),
    PROXY_AUTHENTICATION_REQUIRED(407, "Se requiere autenticación de proxy"),
    REQUEST_TIMEOUT(408, "Tiempo de espera de la solicitud"),
    CONFLICT(409, "Conflicto"),
    GONE(410, "Gone"),
    LENGTH_REQUIRED(411, "Longitud requerida"),
    PRECONDITION_FAILED(412, "Fallo de precondición"),
    PAYLOAD_TOO_LARGE(413, "Carga útil demasiado grande"),
    URI_TOO_LONG(414, "URI demasiado largo"),
    UNSUPPORTED_MEDIA_TYPE(415, "Tipo de medio no soportado"),
    RANGE_NOT_SATISFIABLE(416, "Rango no satisfactorio"),
    EXPECTATION_FAILED(417, "Expectativa fallida"),
    IM_A_TEAPOT(418, "Soy una tetera"),
    MISDIRECTED_REQUEST(421, "Solicitud mal dirigida"),
    UNPROCESSABLE_ENTITY(422, "Entidad no procesable"),
    LOCKED(423, "Bloqueado"),
    FAILED_DEPENDENCY(424, "Dependencia fallida"),
    TOO_EARLY(425, "Demasiado temprano"),
    UPGRADE_REQUIRED(426, "Actualización requerida"),
    PRECONDITION_REQUIRED(428, "Se requiere precondición"),
    TOO_MANY_REQUESTS(429, "Demasiadas solicitudes"),
    REQUEST_HEADER_FIELDS_TOO_LARGE(431, "Campos de encabezado de solicitud demasiado grandes"),
    UNAVAILABLE_FOR_LEGAL_REASONS(451, "No disponible por razones legales"),
    INTERNAL_SERVER_ERROR(500, "Error interno del servidor"),
    NOT_IMPLEMENTED(501, "No implementado"),
    BAD_GATEWAY(502, "Puerta de enlace incorrecta"),
    SERVICE_UNAVAILABLE(503, "Servicio no disponible"),
    GATEWAY_TIMEOUT(504, "Tiempo de espera de la puerta de enlace"),
    HTTP_VERSION_NOT_SUPPORTED(505, "Versión HTTP no soportada"),
    VARIANT_ALSO_NEGOTIATES(506, "Variante también negocia"),
    INSUFFICIENT_STORAGE(507, "Almacenamiento insuficiente"),
    LOOP_DETECTED(508, "Bucle detectado"),
    NOT_EXTENDED(510, "No extendido"),
    NETWORK_AUTHENTICATION_REQUIRED(511, "Se requiere autenticación de red");

    private final int code;
    private final String message;
}
